language: elixir
sudo: false
dist: trusty
elixir:
  - 1.10.4
otp_release:
  - '23.0.4'

script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
